theme: jekyll-theme-minimal
title: Rajesh Krishnan
description: Namaste (नमस्ते). My past was about computers and networks. My practices include yoga, advaita, veganism, and minimalism.
permalink: pretty
