theme: jekyll-theme-minimal
title: Rajesh Krishnan
description: Namaste (नमस्ते). My prior work involved computers and networks. My practice includes veganism, minimalism, yoga, and advaita.
permalink: pretty
