theme: jekyll-theme-minimal
title: Rajesh Krishnan
description: Namaste (नमस्ते). My name is Rajesh Krishnan. My nationality is American, and my ethnicity Asian Indian. My primary languages are English, Tamil, and Hindi; my knowledge of some other Indic languages is at a rudimentary level. Prior to retirement, my professional work involved computers and communication networks. A list of my publications and patents can be found on Google Scholar. My practice includes veganism, minimalism, yoga, and advaita vedanta.
permalink: pretty
